nelmio_api_doc:
    documentation:
        info:
            title: My API
            description: This is the API documentation for my project.
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api
